### ISSUE TITLE
secure derby

### ISSUE THREAD

**Issue by astir13** [az82/docker-derby#1]
Add option to start the derby server in secure authentication mode, according to https://db.apache.org/derby/docs/10.13/security/index.html.

I have code that works and that I'd like to push to a branch here (if I get access) for the maintainter to decide if to accept.

**Comment by az82** [comment]
I would change CMD to ENTRYPOINT, enabling you to provide custom arguments with Docker or Kubernetes. Would that help with your requirements? 

This image was created for using Derby for tests. Therefore, I'm unwilling to secure the image by default or to maintain multiple variants of the image. You can easily roll your own version based on this image.

```shell
docker run --name docker-derby -Dderby.connection.requireAuthentication # ...
```

```yaml
spec:
    containers:
      - name: docker-derby
        image: docker-derby
        args: ["-Dderby.connection.requireAuthentication", "..." ]
```
